### PR TITLE
bind evaluators at load-time

### PR DESCRIPTION
**Pull request by mtrive**
Improve robustness of custom evaluators by binding the corresponding evaluator at load-time, if necessary.

### CODE REVIEW

**Comment by unitystevem** [comment]
Hi Marco,
This is a first for me as a developer at Unity, but I'm going to be a pain about this one and not wave it through immediately. Sorry :)

I have questions. What problem is this PR trying to solve? Prior to the PR, the JSON data specified the CustomEvaluator string directly in each issue (where applicable). There was some redundancy in the form of unnecessary data entries when the strings were empty which I would like to see got rid of, but it was easy to see just by looking at a single issue whether it used a custom evaluator, and which one it used.

This new version relies on a hard-coded dictionary, keyed by an integer issue ID. This feels like it might be suspectible to any change in the data which would cause issues to end up with different numbers. Can we guarantee that this won't happen? My usual workflow for making any changes to the issue databases involves editing the spreadsheet (https://docs.google.com/spreadsheets/d/1y97AQlTCVKb9AYQtzrDA9waOZLaKEsOH8vZdy8vY9Eg/edit#gid=515489513) and re-exporting the JSON from there. I find this much easier and less error-prone than editing the JSON data directly. However, it strikes me if I do this after this PR gets merged, I would not only run the risk of re-adding the customevaluator data you've removed, but I'm also not clear on how the IDs get added. If I rearrange the data in the spreadsheet, will that change the ID ordering? Do IDs come from some other source and I'd over-write them by exporting from the spreadhseet?

Let's chat. I'd like to understand why this change is necessary, and some more about the workflow implications.

**Review by unitystevem — COMMENTED** [review]
Comments added. I don't think I'm happy to approve this one until I have a better idea of what you want to achieve, and what the workflow implications are. (Sorry!)

**Comment by mtrive** [comment]
No worries. This is why I asked you to review it.

First of all, the IDs were assigned programmatically based on their entry order in the file, with a plan to propagate the IDs back to the spreadsheet later on. In retrospect, if I assigned them in the spreadsheet, then exported, would have avoided any confusion. So, this is still a problem that needs to be solved.

With regards to the custom evaluators as strings, I don't think it's very robust solution. We rely on the fact the string corresponds to one of the AnalyzerHelpers functions. Open AnalyzerHelpers.cs in Rider, all those functions are greyed out because supposedly they are not used (though they are).
This seems error-prone to me since ProblemDescriptor and its evaluator are completely decoupled.  What happens if you delete an evaluator by mistake, or remove an entry from the database? Probably you won't know until you run the analysis. This PR, couples them at both compile and load-time.

Ultimately I think we should consider an approach were the entire descriptor is self-contained in its own c# file, similarly to https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/AbstractTypesShouldNotHaveConstructors.cs

Adopting a similar solution means each Descriptor would register itself, so no need to have a hard-coded dictionary.
... but it's a bigger change and needs some discussion, which also must take into consideration Descriptors without evaluators: we have noticed that the current system shows its limitations. In some cases we would like to pass parameters to the method called but it's not possible at the moment. Surely we could add them as additional fields but, again, does not seem a long term solution.

**Comment by unitystevem** [comment]
"What happens if you delete an evaluator by mistake, or remove an entry from the database?"

Removing an entry from the database shouldn't be a problem (except that you're left with a method which will never be called, not great but not the end of the world). Deleting an evaluator by mistake should show up as an error as soon as you click Analyze, so I think it's the sort of problem that would be very quickly identifiable.

That said, Rider thinking the methods are unused could potentially be a concern, if Unity changes its code stripping or something, and suddenly all the methods disappear. So in that sense I can understand your thinking here. And whilst the hard-coded dictionary is a bit uncomfortable, the fact that we have a set of hard-coded, specifically-named methods in AnalyzerHelpers means that we already have a tight coupling between the code and the data, so the dictionary doesn't make things much worse.

I think if issue IDs were explicitly assigned in the spreadsheet rather than programatically and the customevaluator string column was replaced with some kind of TRUE/FALSE boolean, I'd be okay with this. That would mean that things could be added, removed or moved around on the spreadsheet without breaking anything in the tool, unless someone explicitly changes an issue's ID (and if they did, I'd have to hope that they definitely knew what they were doing!). The spreadsheet should perhaps have a custom script to highlight any ID clashes so that they could be fixed before exporting them to JSON. The same checks could probably also be made at load time when the JSON is parsed. What do you think?

**Comment by mtrive** [comment]
"I think if issue IDs were explicitly assigned in the spreadsheet rather than programatically and the customevaluator string column was replaced with some kind of TRUE/FALSE boolean, I'd be okay with this. "
IDs should definitely assigned in the spreadsheet. What I would like though is to generate a separate .cs for each descriptor. Each descriptor will be responsible to register itself to the <Script/Setting>Auditor and also provide its own evaluator if required. That means there won't be any hard-coded dictionary or mixed bag of AnalyzerHelpers functions. Of course, this only works if there is a central knowledge of all existing IDs, which would be the spreadsheet.
This would also allow users to add their own descriptors if they wanted to, perhaps using a specific range of user IDs.

"The spreadsheet should perhaps have a custom script to highlight any ID clashes so that they could be fixed before exporting them to JSON. The same checks could probably also be made at load time when the JSON is parsed."
A load-time check could be implemented, along with some Unit tests. I don't know if I would bother checking IDs before exporting. Also, I am not keen to write Google sheets macros :)

If you agree the Descriptor generation is the way to go, what remains to be defined is how to do it. Again, I don't fancy generating cs files from a spreadsheet. My gut feel is that we could implement something that loads the exported json into the tool (like it does now), then generate the cs Descriptors. We would generate them only after exporting a new json.

How does that sound?

**Comment by unitystevem** [comment]
I'm not sure what you mean by "descriptor" in this context (is each issue/row in the spreadsheet a descriptor?), and I'm not particularly convinced of the need to auto-generate .cs files from the JSON data. I think for the scale of what we're doing, if adding new custom functionality just means writing a new method in AnalyzerHelpers.cs and registering it in the dictionary in the constructor, that's okay. Users could still add their own custom descriptors by modifying that one file in the package (plus the JSON files, I suppose - they won't have access to the spreadsheet but can still modify the JSON locally), and I think that's acceptable. We can even document it in the next documentation pass.

Here's what I think should be done for this PR:
- Add an ID column to the spreadsheet
- Change the customevaluator column from a string to a boolean
- Add validation code on JSON import to ensure that there are no ID clashes

Here's what I think should be added to the task list for future PRs, but which don't need to be a part of this one
- Investigate code gen (probably one for you to pick up)
- Write a Google Sheets validation script for ID clashes that runs on the spreadsheet, for added bonus safety (I don't mind doing that)

**Comment by mtrive** [comment]
"is each issue/row in the spreadsheet a descriptor?"
yes. We create a ProblemDescriptor for each entry in the json file. To be precise, each json entry maps is deserialized into a ProblemDescriptor.

"Add an ID column to the spreadsheet"
that can be done separately though.

"Change the customevaluator column from a string to a boolean"
Assuming you are referring to the column in the spreadsheet, when would we use it? Actually, I am wondering if for the time being we keep a string and we generate some code to register the evaluators. So, the spreadsheet would export:
- a json file
- a cs file to register the custom evaluators

This way we would not need to worry about manually registering evaluators.

"Add validation code on JSON import to ensure that there are no ID clashes"
I can do this.

**Comment by unitystevem** [comment]
Okay, I think I understand your proposal for code generation now. I think you're saying that if you can have the spreadsheet export/JSON import process generate a .cs file to bind descriptors to their custom evaluators, this would eliminate the need for a hand-coded dictionary to map from descriptor IDs to evaluator methods, right? Because that mapping would be autogenerated so any changes to the data which could affect the mappings would also change that code file.

Okay, if you think this is something you can put together reasonably easily, that sounds like the best solution.

How does this work in terms of PR management? Should we close this PR and evaluate the new one when you've done the work, or keep this open and you make changes on this branch?

**Comment by mtrive** [comment]
Let's keep this on hold for now.

**Comment by mtrive** [comment]
let's close this for now

**Pull request closed without merging**
